### ISSUE TITLE
Initial to-do list

### ISSUE THREAD

**Issue by bpbond** [shornum/MA-water#1]
- [x] Create RStudio project file in repository folder and commit it
- [x] Copy your R code file and any needed data file(s) from your spring project into the repository and commit them
- [x] Push to GitHub!
- [x] Add me (bpbond) as a collaborator please :slightly_smiling_face:.  Settings -> Manage Access in repository online

Nice job @shornum !

**Comment by bpbond** [comment]
Adding one more request - please add Steph @stephpenn1 as a collaborator. Then you can close this issue!
